linters:
  enable-all: true
  disable:
    - maligned
    - scopelint
    - interfacer
    - golint
    - exhaustruct
    - exhaustive
    - exhaustivestruct
    - nlreturn
    - tagliatelle
    - varnamelen
run:
  timeout: 5m