linters:
  enable-all: true
  disable:
  # deprecated
    - deadcode
    - ifshort
    - varcheck
    - structcheck
    - nosnakecase
    - maligned
    - scopelint
    - interfacer
    - golint
    - exhaustruct
    - exhaustive
    - exhaustivestruct
    # unused
    - nlreturn
    - tagliatelle
    - varnamelen
run:
  timeout: 5m