# Powered by Application Builder: https://github.com/golift/application-builder
os: linux
dist: bionic
language: go
git:
  depth: false
addons:
  apt:
    packages:
    - ruby-dev
    - rpm
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - zip
    - debsigs
#    - gnupg
    - expect
go:
  - 1.15.x
services:
  - docker
install:
  - mkdir -p $(go env GOPATH)/bin
  - curl -sL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
  - rvm install 2.6.0
  - rvm 2.6.0 do gem install --no-document fpm
before_script:
  # Create your own deploy key, tar it, and encrypt the file to make this work. Optionally add a bitly_token file to the archive.
  - openssl aes-256-cbc -K $encrypted_3d4e59aeeb92_key -iv $encrypted_3d4e59aeeb92_iv -in .secret_files.tar.enc -out .secret_files.tar -d
  - tar -xf .secret_files.tar
#  - gpg --import gpg.signing.key
  - rm -f gpg.signing.key .secret_files.tar
  - source .metadata.sh
script:
  # Test Go and Docker.
  - # make test
  - make docker
  # Test built docker image.
  - docker run $BINARY -v 2>&1 | grep -Eq "^$BINARY v$VERSION"
  # Build everything
  - rvm 2.6.0 do make release
after_success:
  # Display Release Folder
  - ls -l release/
  # Setup the ssh client so we can clone and push to the homebrew formula repo.
  # You must put github_deploy_file into .secret_files.tar.enc
  # This is an ssh key added to your homebrew forumla repo.
  - |
    mkdir -p $HOME/.ssh
    declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
    echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> $HOME/.ssh/config
    [ ! -f github_deploy_key ] || (mv github_deploy_key $SSH_FILE \
      && chmod 600 "$SSH_FILE" \
      && printf "%s\n" \
        "Host github.com" \
        "  IdentityFile $SSH_FILE" \
        "  StrictHostKeyChecking no" \
        "  LogLevel ERROR" >> $HOME/.ssh/config)
deploy:
  - provider: releases
    token:
      # to get a secure api key, run: travis setup releases
      # make a copy of this file first because that command will change it.
      # or: make a new key manually at https://github.com/settings/tokens/new
      # then: echo <NEW_KEY_FROM_GH> | travis encrypt
      secure: "ss7VYWtUf3VWDsWbDVWZCIq7cOJZ7G2w3rlIB95Du0xjH2lKX3j3pz8nVVRwa549X1oXrdL59ruixnhn1Oj/qaItB2DoAyS/F1xUjKDriTX2m31QHdMppeVTP4ajVrGEhoqfNXMHp53tbCtwZEg09yYryM6Y53tcznTWrxqmBWejC7oXNSbFatLwGTaVPQT4dB1sB72dQcqhZaWeQHI9tqM5rOtyT9hpx1JTp6twUTfI0u2gz/T3Yyz3ZU2LyQUWv6vabN1VeRTTvSv+yEmB3KUwk0bz765sECeuHVwi/S0DNhM+6h9F1AziISAtNuXBzhxy5uyqBKw6kIZQUHSpKZdMogUdgp9Sbs4vmO7nVcmA0NYL0ggGxlKio8ZqRyXIyWx5+BpkBICT7RzU4Zc1HsIGcuEPazF1nuA3HLIAyPFdM8NB2ttxL4xAue5RdaGONyLizQZTCo/9XX00LtaytpPki9eYWIAZPf9ta2Ngg3k72FLXEfwYJ/annaJr7Gp+YnFKMbcwJNPB2zQrUXIu2b2i9eLdVGE/U6PVZAGkP30y0q9FCc+S4VieqMWP0yd/oJ/0i8HXjd7HRjYkT4XmhvLloLToM5adcgKpg03cJL9x6eVGtX+dENtecD3tBEGHdM6Qx94mSOt0qffgMuKC7B7TvzR8a71mYZo1PwPmt3E="
    overwrite: true
    skip_cleanup: true
    cleanup: false
    file_glob: true
    file: release/*
    on:
      tags: true
  - provider: script
    script: scripts/formula-deploy.sh
    on:
      tags: true
