runtime: go112

handlers:
- url: /(.*\.(gif|png|jpg|svg|ico|txt|js|css))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg|svg|ico|txt|js|css)$
  secure: always
  redirect_http_response_code: 301
- url: /(browserconfig.xml|site.webmanifest|gpgkey)$
  static_files: static/\1
  upload: static/(gpgkey|.*\.(xml|webmanifest))$
  secure: always
  redirect_http_response_code: 301
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
