# [[ Production Configuration File for golift.io Code Repo ]]

host: golift.io
title: Go Lift
logo_url: https://docs.golift.io/apple-touch-icon.png
description: Go Language Code Libraries - amazing!
links:
  - title: Docker
    url: https://hub.docker.com/u/golift
  - title: GitHub
    url: https://github.com/golift
  - title: Discord
    url: https://golift.io/discord
  - title: Package Cloud
    url: https://packagecloud.io/golift

# If this is set, a source link to this path is displayed on the index page.
# protip: setup a redirect for /source - see below.
src: /source

# This controls the max-age cache-control value.
# This setting is global, can be set per path too.
cache_max_age: 86400

# This is the path used for badgedata. Most people will unset this to turn off badgedata.
bd_path: "/bd/"

# These paths will be redirected if redir is not ""
# This setting is global, can be set per path too.
# Redirection works like this: if the path matches,
# the sub-path is then checked for one of these strings.
# If sub-path also matches, the client is redirected to
# $redir + $subpath (subpath doesn't contain matched $path)
redir_paths: ["tar.gz", "wiki", "releases"]

# Paths that get handled by this app.
paths:
  /badgedata:
    repo: https://github.com/golift/badgedata
    redir: https://github.com/golift/badgedata
  /cnfg:
    repo: https://github.com/golift/cnfg
    redir: https://github.com/golift/cnfg
  /cnfgfile:
    repo: https://github.com/golift/cnfgfile
    redir: https://github.com/golift/cnfgfile
  /rotatorr:
    repo: https://github.com/golift/rotatorr
    redir: https://github.com/golift/rotatorr
  /deluge:
    repo: https://github.com/golift/deluge
    redir: https://github.com/golift/deluge
  /imessage:
    repo: https://github.com/golift/imessage
    redir: https://github.com/golift/imessage
  /subscribe:
    repo: https://github.com/golift/subscribe
    redir: https://github.com/golift/subscribe
  /ffmpeg:
    repo: https://github.com/golift/ffmpeg
    redir: https://github.com/golift/ffmpeg
  /starr:
    repo: https://github.com/golift/starr
    redir: https://github.com/golift/starr
  /securityspy:
    repo: https://github.com/golift/securityspy
    redir: https://github.com/golift/securityspy
  /version:
    repo: https://github.com/golift/version
    redir: https://github.com/golift/version
  /xtractr:
    repo: https://github.com/golift/xtractr
    redir: https://github.com/golift/xtractr
  /qbit:
    repo: https://github.com/golift/qbit
    redir: https://github.com/golift/qbit
  /datacounter:
    repo: https://github.com/golift/datacounter
    redir: https://github.com/golift/datacounter

  # Unused Examples.
  /david/:
    repo: https://github.com/davidnewhall/
    wildcard: true
  /captain-:
    repo: https://github.com/davidnewhall/
    wildcard: true

  # No repos.
  # Giving an item a "name" puts it in the Applications list.
  /discord:
    redir: https://discord.gg/YrWnVzjWMC
    redir_paths: [""]
  /turbovanityurls:
    name: "Turbo Vanity URLs"
    redir: https://github.com/golift/turbovanityurls
    redir_paths: [""]
  /unifi-poller:
    name: "UnPoller"
    redir: https://github.com/unpoller/unpoller
    redir_paths: [""]
  /unpoller:
    name: "UnPoller"
    redir: https://github.com/unpoller/unpoller
    redir_paths: [""]
  /secspy:
    name: "SecSpy"
    redir: https://github.com/davidnewhall/secspy
    redir_paths: [""]
  /unpackerr:
    name: "Unpackerr"
    redir: https://github.com/davidnewhall/unpackerr
    redir_paths: [""]
  /motifini:
    name: "Motifini"
    redir: https://github.com/davidnewhall/motifini
    redir_paths: [""]
  /notifiarr:
    name: "Notifiarr"
    redir: https://github.com/Notifiarr/notifiarr
    redir_paths: [""]
  /hello-world:
    name: "Hello World"
    redir_paths: [""]
    redir: https://github.com/golift/application-builder
  /source:
    redir_paths: [""]
    redir: https://github.com/golift/turbovanityurls
