# [[ Production Configuration File for golift.io Code Repo ]]

# This is the host path used for godoc links, etc.
# Determined automatically if not set here.
host: golift.io

# Used as the title of the index page.
title: Go Lift Code

# Displayed as links on the index page.
links:
  - title: Docker
    url: https://hub.docker.com/u/golift
  - title: GitHub
    url: https://github.com/golift

# If this is set, a source link to this path is displayed on the index page.
# protip: setup a redirect for /source - see below.
src: /turbovanityurls

# This controls the max-age cache-control value.
# This setting is global, can be set per path too.
cache_max_age: 86400

# This is the path used for badgedata. Most people will unset this to turn off badgedata.
bd_path: "/bd/"

# These paths will be redirected if redir is not ""
# This setting is global, can be set per path too.
# Redirection works like this: if the path matches,
# the sub-path is then checked for one of these strings.
# If sub-path also matches, the client is redirected to
# $redir + $subpath (subpath doesn't contain matched $path)
redir_paths: ["tar.gz", "wiki", "releases"]

# Paths that get handled by this app.
paths:
  /badgedata:
    repo: https://github.com/golift/badgedata
    redir: https://github.com/golift/badgedata

  /unifi:
    repo: https://github.com/golift/unifi
    redir: https://github.com/golift/unifi
    image_url: https://docs.golift.io/svg/ubiquiti_color.svg
    description: Package unifi provides API methods to extract client and device data from a UniFi Controller.
      Methods are also provided to marshal the data into InfluxDB data points that can be used to create visualizations.
      This library is used by UniFi Poller to collect and graph network data.
    links:
      - url: https://golift.io/unifi-poller
        title: "UniFi Poller"
      - url: http://grafana.com/dashboards?search=unifi-poller
        title: "Grafana Dashboards"
    cache_max_age: 2345

  /deluge:
    repo: https://github.com/golift/deluge
    redir: https://github.com/golift/deluge
  /imessage:
    repo: https://github.com/golift/imessage
    redir: https://github.com/golift/imessage
  /subscribe:
    repo: https://github.com/golift/subscribe
    redir: https://github.com/golift/subscribe
  /ffmpeg:
    repo: https://github.com/golift/ffmpeg
    redir: https://github.com/golift/ffmpeg
  /starr:
    repo: https://github.com/golift/starr
    redir: https://github.com/golift/starr
  /securityspy:
    repo: https://github.com/golift/securityspy
    redir: https://github.com/golift/securityspy

  # Unused Examples.
  /david/:
    repo: https://github.com/davidnewhall/
    wildcard: true
  /captain-:
    repo: https://github.com/davidnewhall/
    wildcard: true

  # No repos.
  /unifi-poller:
    redir: https://github.com/davidnewhall/unifi-poller
  /secspy:
    redir: https://github.com/davidnewhall/secspy
  /unpacker-poller:
    redir: https://github.com/davidnewhall/unpacker-poller
  /source:
    redir_paths: [""]
    redir: https://github.com/golift/turbovanityurls
